### ISSUE TITLE
libs a little bit old

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#5] opened 2017-01-09 07:00 UTC
the libs used by the teleprompter are outdated (jquery cookie dont exists formely any more), that is a problem because:

1. this is a great proyect whit so much potencial ( i tested many teleprompter´s before this), but people will take apart because uses jquery 1 instead 3, by example.

 1. make dificult to interoperate whit other libs, i planned create a sync version named "CliMas" (game of words) that allow to multiples instances see the same text, but some libs nedd jquery 2 or 3 so ended whit various versions of jquery...a mess

 1. buggy performance in phone browsers, i guees is for new versions libs has better code (?)

 1. when added new features will end with various versions of jquery or font awesome (see 2 )

**Comment by manifestinteractive** [comment] 2017-01-09 10:48
As an open source project, I am open to any Pull Request that would update the libraries in a way that fixes the issues you mentioned.  I agree the libraries are old ... but since they are on a CDN that will likely not being going away anytime soon, I feel like it is safe to leave things working as they are until such time where things are broken.

But if a Pull Request came in with all new fresh libraries and all functionality worked as before, that would be great :)  So I will leave this ticket open for anyone that wants to take that on.

I personally don't see a reason to fix something that is not currently broken.  Mobile Phones were never really a targeted device to begin with ( this project was designed for tablet size screens or larger ).  But as I said, if someone wanted to make the changes, I have no objections :)

**Comment by manifestinteractive** [comment] 2021-06-12 09:24
Closing this out as no action was taken on it.

**Closed as completed by manifestinteractive** 2021-06-12 09:24 UTC
Labels: Feature Request, Won't Fix
